apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dsh3xl53q-go
  janus-idp.io/tekton: dsh3xl53q-go
  backstage.io/kubernetes-id: dsh3xl53q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dsh3xl53q-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
