apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dsh3xl53q-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dsh3xl53q-go 
  name: dsh3xl53q-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dsh3xl53q-go 
